version: '3.1'
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data:/data/db'
    environment:
      POSTGRES_INITDB_ROOT_USERNAME: ${POSTGRES_USER}
      POSTGRES_INITDB_ROOT_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:5050
    depends_on:
      - postgres
    environment:
      ME_CONFIG_POSTGRES_ADMINUSERNAME: ${POSTGRES_USER}
      ME_CONFIG_POSTGRES_ADMINPASSWORD: ${POSTGRES_PASSWORD}
      ME_CONFIG_POSTGRES_PORT: ${POSTGRES_PORT}
      ME_CONFIG_POSTGRES_SERVER: ${POSTGRES_HOST}

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - postgres

  shipping-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7070:8080
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      IMAGE: ${IMAGE}
      GIT_COMMIT: ${GIT_COMMIT}
      SPRING_BOOT_PROFILE: ${SPRING_BOOT_PROFILE}
      POSTGRES_AUTH_DB: ${POSTGRES_AUTH_DB}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_ARGS: ${POSTGRES_ARGS}
      LEANX_ID: ${LEANX_ID}
      LOGGING_LEVEL_API: ${LOGGING_LEVEL_API}
      LOGGING_LEVEL_POSTGRES: ${LOGGING_LEVEL_POSTGRES}
      LOG_BODY: ${LOG_BODY}
      DPE_HOST: ${DPE_HOST}
      DPE_URI: ${DPE_URI}
      DPE_APPID: ${DPE_APPID}
      DPE_MS_HOST: ${DPE_MS_HOST}
      DPE_MS_URI: ${DPE_MS_URI}
      DPE_MS_API_KEY: ${DPE_MS_API_KEY}
      CNC_HOST: ${CNC_HOST}
      CNC_URI: ${CNC_URI}
      CNC_APPID: ${CNC_APPID}
      DPE_FAILOVER_HOST: ${DPE_FAILOVER_HOST}
      DPE_FAILOVER_URI: ${DPE_FAILOVER_URI}
      DPE_FAILOVER_APPID: ${DPE_FAILOVER_APPID}
      SSM_STORE_HOST: ${SSM_STORE_HOST}
      SSM_STORE_URI: ${SSM_STORE_URI}
      SSM_STORE_APIKEY: ${SSM_STORE_APIKEY}
      SSM_STORE_SECRET: ${SSM_STORE_SECRET}
      SSM_STORE_RADIUS: ${SSM_STORE_RADIUS}
      SSM_STORE_PAGE: ${SSM_STORE_PAGE}
      SSM_STORE_PAGE_SIZE: ${SSM_STORE_PAGE_SIZE}
      PUDO_AGG_HOST: ${PUDO_AGG_HOST}
      PUDO_AGG_URI: ${PUDO_AGG_URI}
      PUDO_AGG_AUTHORIZATION: ${PUDO_AGG_AUTHORIZATION}
      PUDO_AGG_RADIUS: ${PUDO_AGG_RADIUS}
      PUDO_ID_AGG_HOST: ${PUDO_ID_AGG_HOST}
      PUDO_ID_AGG_URI: ${PUDO_ID_AGG_URI}
      PUDO_AGG_STORE_URI: ${PUDO_AGG_STORE_URI}
      PUDO_AGG_STORE_PAGE: ${PUDO_AGG_STORE_PAGE}
      PUDO_AGG_STORE_PAGE_SIZE: ${PUDO_AGG_STORE_PAGE_SIZE}
      GOOGLE_API_HOST: ${GOOGLE_API_HOST}
      GOOGLE_API_URI: ${GOOGLE_API_URI}
      SECRET_GOOGLE_API_KEY: ${SECRET_GOOGLE_API_KEY}
      HTTP_CONNECT_TIMEOUT_MILLIS: ${HTTP_CONNECT_TIMEOUT_MILLIS}
      DPE_HTTP_READ_TIMEOUT_MILLIS: ${DPE_HTTP_READ_TIMEOUT_MILLIS}
      SSM_HTTP_READ_TIMEOUT_MILLIS: ${SSM_HTTP_READ_TIMEOUT_MILLIS}
      PUDO_AGG_HTTP_READ_TIMEOUT_MILLIS: ${PUDO_AGG_HTTP_READ_TIMEOUT_MILLIS}
      GEO_HTTP_READ_TIMEOUT_MILLIS: ${GEO_HTTP_READ_TIMEOUT_MILLIS}
      CACHE_EXPIRY_SECONDS: ${CACHE_EXPIRY_SECONDS}
      HTTP_MAX_CONNECTIONS: ${HTTP_MAX_CONNECTIONS}
	  HTTP_CONN_MAX_IDLE_TIME_SEC: ${HTTP_CONN_MAX_IDLE_TIME_SEC}
      HTTP_MAX_CONN_LIFE_TIME_SEC: ${HTTP_MAX_CONN_LIFE_TIME_SEC}
      HTTP_ACQUIRE_TIMEOUT_SEC: ${HTTP_ACQUIRE_TIMEOUT_SEC}
      HTTP_EVICT_SEC: ${HTTP_EVICT_SEC}
      ADDRESS_LINES_POSTBOX-JSON-CONTENT: ${ADDRESS_LINES_POSTBOX-JSON-CONTENT}
      USPS-CARRIERS: ${USPS-CARRIERS}
      CHANNELS: ${CHANNELS}
      MILITARY-STATES-JSON-CONTENT: ${MILITARY-STATES-JSON-CONTENT}
  redis:
    container_name: redis
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always

volumes:
  postgres_data:
    driver: local