# REGION scoped values - high precedence (on match, overwrites both DEFAULT and REGION scoped values)
global:
  hostname: com-next.api.3stripes.io
  postgresArgs: "ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  postgresWriterHost: "com-next-prd-postgres-eu.cluster-cuat1uig9xmd.eu-west-1.rds.amazonaws.com"
  postgresReaderHost: "com-next-prd-postgres-eu.cluster-ro-cuat1uig9xmd.eu-west-1.rds.amazonaws.com"
  postgresWriterInitialSize: "100"
  postgresWriterMaxSize: "500"
  postgresWriterMaxIdleTimeMin: "30"
  postgresWriterMaxCreateConnTimeSec: "10"
  postgresReaderInitialSize: "100"
  postgresReaderMaxSize: "500"
  postgresReaderMaxIdleTimeMin: "30"
  postgresReaderMaxCreateConnTimeSec: "10"
  dpe_host: https://eai.omnihub.3stripes.net
  dpe_uri: eai/delivery/options/V2
  dpe_ms_host: https://omnideliverypromise.api.3stripes.io
  dpe_ms_uri: getDeliveryOptions/v2
  dpe_failover_host: https://omnihub.api.3stripes.io
  dpe_failover_uri: deliveryPromise/V2
  cncHost: https://eai.omnihub.3stripes.net
  cncUri: /eai/clickncollect/availability/V2
  ssmStoreHost: https://omni.api.3stripes.io
  ssmStoreUri: ssm/stores
  pudoAggregatorHost: http://production-tf-pudo-aggregator.ecom-tf.svc.cluster.local:8000
  pudoAggregatorLocationSearchURI: location/search
  pudoIdAggregatorLocationSearchURI: location
  pudoAggregatorStoreURI: store
  redisHost: "basket-commerce-next-prd.acx6dp.ng.0001.euw1.cache.amazonaws.com"
